version: '3.8'  

services:
  frontend:
    image: sasiramakrishnan/course-frontend:latest  
    build:
      context: ./frontend  
      dockerfile: Dockerfile 
    ports:
      - "3000:3000"  
    environment:
      - NODE_ENV=production  

 
